@startuml
skinparam BackgroundColor transparent
skinparam ArrowColor #Black
skinparam ActorBackgroundColor #White
skinparam ParticipantBackgroundColor #White
skinparam NoteBackgroundColor #White
skinparam SequenceLifeLineBorderColor #Black

participant "Remote\nEbMS Adapter" as remote
participant "EbMS Adapter\n(EbMSMessageService)" as ebms
actor Application as app

remote -> ebms : EbMS message
ebms --> remote : Acknowledgment

loop poll
  app -> ebms : getUnprocessedMessageIds(filter, maxNr)
  ebms --> app : List<messageId>
end

app -> ebms : getMessage(messageId, process=true)
ebms --> app : message
note right of app : alternative:\ngetMessage(messageId, false)\nthen processMessage(messageId)

@enduml
