@startuml
skinparam BackgroundColor transparent
skinparam ArrowColor #Black
skinparam ActorBackgroundColor #White
skinparam ParticipantBackgroundColor #White
skinparam NoteBackgroundColor #White
skinparam SequenceLifeLineBorderColor #Black

actor Application as app
participant "EbMS Adapter\n(CPAService)" as ebms

app -> ebms : validateCPA(cpa)
ebms --> app : validation result

app -> ebms : insertCPA(cpa, overwrite)
ebms --> app : cpaId

app -> ebms : getCPAIds()
ebms --> app : List<cpaId>

app -> ebms : getCPA(cpaId)
ebms --> app : cpa

app -> ebms : deleteCPA(cpaId)
ebms --> app : ok

@enduml
